# Generated by Django 5.2.5 on 2025-08-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_contact_user_contact_name_blogsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
