# Generated by Django 5.2.5 on 2025-09-05 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.PositiveBigIntegerField(verbose_name='Amount')),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='waiting', max_length=255)),
                ('payment_time', models.DateTimeField(null=True)),
                ('payment_url', models.URLField(blank=True, max_length=1255, null=True, verbose_name='Payment url')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
