from django.db import migrations, models
import uuid
import django.db.models.deletion
from django.core.validators import MinValueValidator, MaxValueValidator


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='DesignCategory',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('type', models.CharField(max_length=20, choices=[('3d','3D Max Product'), ('interior','Interior Design')])),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=220, unique=True, blank=True)),
            ],
            options={'ordering':['name'], 'verbose_name':'Design Category', 'verbose_name_plural':'Design Categories'}
        ),
        migrations.CreateModel(
            name='DesignAsset',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True, blank=True)),
                ('cover_image', models.ImageField(upload_to='designs/covers/', blank=True, null=True)),
                ('price', models.DecimalField(max_digits=12, decimal_places=2, validators=[MinValueValidator(0)])),
                ('discount', models.PositiveIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(90)])),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='designs.designcategory')),
            ],
            options={'ordering':['-created_at'], 'verbose_name':'Design Asset', 'verbose_name_plural':'Design Assets'}
        ),
        migrations.CreateModel(
            name='AssetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='designs/gallery/')),
                ('alt_text', models.CharField(max_length=180, blank=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='designs.designasset')),
            ],
            options={'ordering':['ordering','id'], 'verbose_name':'Asset Image', 'verbose_name_plural':'Asset Images'}
        ),
    ]
# Generated by Django 5.2.4 on 2025-08-25 03:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='designs/covers/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)])),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Design Asset',
                'verbose_name_plural': 'Design Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('type', models.CharField(choices=[('3d', '3D Max Product'), ('interior', 'Interior Design')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
            ],
            options={
                'verbose_name': 'Design Category',
                'verbose_name_plural': 'Design Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='designs/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=180)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='designs.designasset')),
            ],
            options={
                'verbose_name': 'Asset Image',
                'verbose_name_plural': 'Asset Images',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.AddField(
            model_name='designasset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='designs.designcategory'),
        ),
    ]
