# Generated by Django 5.2.5 on 2025-08-27 06:01

import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_designreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignAssetTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Design Asset Translation',
                'db_table': 'designs_designasset_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='DesignCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Design Category Translation',
                'db_table': 'designs_designcategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.AlterModelOptions(
            name='designcategory',
            options={'ordering': ['created_at'], 'verbose_name': 'Design Category', 'verbose_name_plural': 'Design Categories'},
        ),
        migrations.RenameIndex(
            model_name='designreview',
            new_name='designs_des_created_adc5af_idx',
            old_name='designs_des_created_57af1a_idx',
        ),
        migrations.RemoveField(
            model_name='designasset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='designasset',
            name='name',
        ),
        migrations.RemoveField(
            model_name='designasset',
            name='price',
        ),
        migrations.RemoveField(
            model_name='designcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='designcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='designassettranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='designs.designasset'),
        ),
        migrations.AddField(
            model_name='designcategorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='designs.designcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='designassettranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='designcategorytranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
