# Generated by Django 5.2.5 on 2025-08-24 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='products_discount_range',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='products_stock_not_negative',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_slug_5e91f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_sku_fe2039_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_is_acti_8e1d32_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_created_a77fb9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating_average',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_reserved',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty_months',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_grams',
        ),
        migrations.RemoveField(
            model_name='product',
            name='year_of_manufacture',
        ),
    ]
